####
## 예외처리
####
#### ► [_01_TryCatch_230425] & [_02_Catch_230425]
- 프로그램 실행 시 발생할 수 있는 예외의 발생에 대비한 코드를 작성하는 예외처리 실습
- (1) try-catch문: 예외가 발생할 가능성이 있는 하나의 try블럭과 여러 예외를 처리할 수 있는 하나 이상의 catch블럭으로 구성
- (2) 멀티 catch문: '|' 기호를 사용해 여러 catch블럭을 하나의 catch블럭으로 연결
####
#### ► [_03_Throw_230426]
- 키워드 throw를 사용해 프로그래머가 고의로 예외를 발생시키는 실습
####
#### ► [_04_Finally_230426]
- 예외 발생 여부와 관계없이 항상 수행되어야 할 코드를 포함할 목적으로 사용하는 finally 블럭 실습
- 💡 finally블럭은 ty-catch문의 마지막에 위치한다.
- 💡 예외가 발생한 경우엔 'try -> catch -> finally', 예외가 발생하지 않은 경우엔 'try -> finally' 순으로 실행된다.
####
#### ► [_05_TryWithResources_230426]
- 예외 발생 여부와 관계없이 항상 수행되어야 할 코드를 포함할 목적으로 사용하는 finally 블럭 실습
- 💡 finally블럭은 try-catch문의 마지막에 위치한다.
- 💡 예외가 발생한 경우엔 'try -> catch -> finally', 예외가 발생하지 않은 경우엔 'try -> finally' 순으로 실행된다.
####
